{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinpoet/1.19.0-KMP-SNAPSHOT/kotlinpoet-1.19.0-KMP-SNAPSHOT.module",
    "group": "com.squareup",
    "module": "kotlinpoet",
    "version": "1.19.0-KMP-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.0.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinpoet-js-1.19.0-KMP-SNAPSHOT.klib",
          "url": "kotlinpoet-js-1.19.0-KMP-SNAPSHOT.klib",
          "size": 435091,
          "sha512": "a2a4a86316504852286093e260e1c364403b632c0554fd962f4d9b64a51d56d71f788acedcc3bd3480a164879447698757efe80a6860d5c5d15d9ce044c0b24a",
          "sha256": "c2961b50246683da4600016436cf86c82ee9d07597822f9e626c5eca5bb9b2ad",
          "sha1": "5fb37aaf773bce92d66e8d59c82990e85bfca42a",
          "md5": "e7994f9b49ebb262e667f6738591b7df"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.0.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinpoet-js-1.19.0-KMP-SNAPSHOT.klib",
          "url": "kotlinpoet-js-1.19.0-KMP-SNAPSHOT.klib",
          "size": 435091,
          "sha512": "a2a4a86316504852286093e260e1c364403b632c0554fd962f4d9b64a51d56d71f788acedcc3bd3480a164879447698757efe80a6860d5c5d15d9ce044c0b24a",
          "sha256": "c2961b50246683da4600016436cf86c82ee9d07597822f9e626c5eca5bb9b2ad",
          "sha1": "5fb37aaf773bce92d66e8d59c82990e85bfca42a",
          "md5": "e7994f9b49ebb262e667f6738591b7df"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "kotlinpoet-js-1.19.0-KMP-SNAPSHOT-sources.jar",
          "url": "kotlinpoet-js-1.19.0-KMP-SNAPSHOT-sources.jar",
          "size": 121114,
          "sha512": "4567995141376d94aca7a88f16a417aa94aeae69fdf2a7d1417d142d1f3a334ee317c6059cd47826ef3604f65acc6786f41603ee8e420f198f9875cf007e18c9",
          "sha256": "55e375e3bf4d9aa44156499bf710bb1daec17c5da7a7b384819945864ff85fc3",
          "sha1": "4804d387f35e8e0cff7a4628866b32a12add0a31",
          "md5": "23772a0fb4d76c66fb591d8d2c298e8d"
        }
      ]
    }
  ]
}
